//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muntajat_v1._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int Id { get; set; }
        public int CountryId { get; set; }
        public int CityId { get; set; }
        public string District { get; set; }
        public string Street { get; set; }
        public Nullable<double> LocationLatitude { get; set; }
        public Nullable<double> LocationLongitude { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
    }
}
