//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muntajat_v1._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderLines = new HashSet<OrderLine>();
        }
    
        public int Id { get; set; }
        public int BuyerId { get; set; }
        public int SellerId { get; set; }
        public string Status { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<bool> IsPayed { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<int> ItemsNum { get; set; }
        public Nullable<double> DeductedAmount { get; set; }
        public Nullable<bool> IsPromotion { get; set; }
        public Nullable<int> PromotionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLine> OrderLines { get; set; }
    }
}
